# Generated by Django 4.2 on 2026-03-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('state', models.CharField(choices=[('Maharashtra', 'Maharashtra'), ('Karnataka', 'Karnataka'), ('Goa', 'Goa')], max_length=20)),
                ('city', models.CharField(choices=[('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Bangalore', 'Bangalore')], max_length=20)),
                ('pincode', models.CharField(max_length=6)),
                ('branch', models.CharField(choices=[('CS', 'CS'), ('IT', 'IT'), ('ENTC', 'ENTC')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
